language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "deployment-exercise-test";' -U postgres
before_deploy:
- rm -rf node_modules
deploy:
  provider: heroku
  api_key:
    secure: NhHv2iSvV14DILcI/QOP+T21xT0jG4QAonV1MUoHFMnC2FZh9xy9+n/i87zhCzC1l49OamuOj/a++SpJo/PF+KwqmzyMgJfFy0LWOx+D/lZvt/RfxbMPw0yd1+BwXvHnSDkkBDchWyWxjt46Hcv5EYjBGJMd6DksfuZcmWTIuPpA7D5m/N0mCYZFzi4yZ3KUgeCMPfvlP88UFoqN4QwmdAOSijPzuVFjCxG8fdMo+XDpOqv9PgZlDsi+Uvd0C/PNfJaNlkz8DQOWTOnSmyN5jnfdbun2/ru5vUpRJ4RChaIuCxdLiTQcX4JwWxuvc1vI8WpduAYcEXo1tPBUN7uh9ocNan2sR175Gkna8ZpTL8lJlBUQoq1t+2ivGFiFLwhd0nzUISskZjEY8fb7xgF1/CCrvID1XT+LFAAS6xcwGqPuKAtna2gDdctHiWHFLDIpgImeD98+OZgdeenVuKotggqEDzU0vAbktv94pvnlVHu/+7UH4bAmJP+6pGZoYQAtPcEC/wVRcwpWy5Uu+o0bO/4knnvNBNOZB+5L8Eyj8NKlBIVKOneokcsMx1zbkv6Wzidv4Jv7UVvgaeJfw/MbMexadc0tfKwMenFdq156luA5FIeC9R8z33p+TwcWwd1+HVvOQ8yTmn1xD5Pml+DjQegVbzXwAP/+GZtLUeZFsZ4=
  app: shielded-hamlet-41176
  on:
    repo: lah5175/PairExercise.Deployment.Solution
