language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "deployment-exercise-test";' -U postgres
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: shielded-hamlet-41176
  api_key:
    secure: qeZInPhUkdY13BXe4vYdMm56zQiOuuVptUH0x2aOJrZaniTUhFiAki3pzjLko4Y6KDTsNLlY4APRZnBw0nIIBvq/4+KT8++XP5SGU+/Qpft1562UumYWkl2xQGQTwI6sBlV25BJumurvLTBMd/EqzlA4t6DYo5buSE8o5OJguYRuuVzDT+GCXp8hvA+Z5L+jMgHeNXh2li/tgXra9EcscG6o7di5ICz8O1Vu2+Q1oo1JAlywLK8TsUBUhds2QyPKrshb7zcKiNBXu3lBZfe5wobEdZYyGZOn0xKvHdXu1I7FU4xQOtiAogiqJPlFqHR7uawHneL+k2z1jPvt+vfSO5TH63UmEEbaelV+1GsGC52B/QxHhfAxahM4UoGyw8mSArzP1SdlTUQYuu6VvAkc3iB8W7avDa3wlqZcwoVmo5ouywIUOAcLwdqYBbkH08OKCyk8vWTAx7jFBsqO8snSTxcY3N901TX/1a5uh0SGtzywWkfsI7koGeHRJf6DdO4/ClL65IwUa0cOpqUztBa/g+iLz6iEkDUmzZb09k0SiDdIhdDZtYqTvUzFU1Ij54v6W7FGIP8FnR4/VSA7outb3vT6RkBCZ3rQ3bbnuoXxmLXDJM1yIvd8TTun4hDnR6jHTTEAdB53iUg10BSV9FolQpD4P0e43zqJKLPY4qTtjhI=
